plugins {
    id 'fabric-loom' version '1.14.10'
    id 'maven-publish'
}

version = project.mod_version
group   = project.maven_group

repositories {
    maven { url 'https://maven.terraformersmc.com/releases' }
}

base {
    archivesName = project.archives_base_name + "-1.21.11"
}

sourceSets {
    main {
        java { srcDirs rootProject.file('common/src/main/java'), 'src/main/java' }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
}

processResources {
    inputs.property 'version', project.version
    filteringCharset 'UTF-8'
    filesMatching('fabric.mod.json') { expand 'version': project.version }
}

tasks.withType(JavaCompile).configureEach { it.options.release = 21 }

java {
    withSourcesJar()
    sourcesJar { duplicatesStrategy = DuplicatesStrategy.EXCLUDE }
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}
